# Generated by Django 2.2.6 on 2019-10-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedder', models.CharField(db_index=True, max_length=128)),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=256)),
                ('genres', models.CharField(max_length=128)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('cluster', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('embedder', 'movie_id'), name='unique_movie_per_embedding'),
        ),
    ]
