# Generated by Django 2.2.6 on 2019-11-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_edge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='stddev',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
