# Generated by Django 2.2.6 on 2019-11-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_edge', '0002_auto_20191105_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stddev',
            new_name='std',
        ),
    ]
