# Generated by Django 2.2.6 on 2019-11-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_edge', '0003_auto_20191105_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='std',
            field=models.FloatField(null=True),
        ),
    ]
