# Generated by Django 2.2.6 on 2019-11-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_edge', '0007_auto_20191105_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
